"""Find the number of distinct terms in the sequence generated by a^b for integers a and b satisfying 2 <= a <= 100 and
2 <= b <= 100."""

sequence = set()
for a in range(2, 101):
    for b in range(2, 101):
        sequence.add(a ** b)

print(len(sequence))
