"""Pentagonal numbers are generated by the formula, Pn=n(3n?1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 ? 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk ? Pj| is
minimised; what is the value of D?"""

# make list containing 3000 pentagonal numbers
pentagonal_numbers = [n * (3*n-1) // 2 for n in range(1, 3001)]

d = 1e+30
for x in range(len(pentagonal_numbers)):
    for y in range(x + 1, len(pentagonal_numbers)):
        if ((pentagonal_numbers[x]+pentagonal_numbers[y]) in pentagonal_numbers) and \
                ((pentagonal_numbers[y]-pentagonal_numbers[x]) in pentagonal_numbers):
            d = min(d, pentagonal_numbers[y]-pentagonal_numbers[x])

print(d)
